./examples/opam/fn-arg.ml:1: a ALWAYS
./examples/opam/fn-arg.ml:1: b NEVER
./examples/opam/fn-arg.ml:3: b NEVER
./examples/opam/fn-arg.ml:3: b ALWAYS
./examples/opam/fn-arg.ml:7: a ALWAYS
./examples/opam/fn-arg.ml:7: b NEVER
./examples/opam/fn-arg.ml:9: c ALWAYS
./examples/opam/fn-arg.ml:9: b ALWAYS
./examples/opam/fn-arg.ml:11: b ALWAYS
./examples/opam/fn-arg.ml:11: b ALWAYS
