(lang dune 3.20)

(name using_dune)

(wrapped_executables false)

(map_workspace_root false)

(generate_opam_files true)

(package
 (name using_dune)
 (allow_empty)
 (depends ppx_deriving)
)

; See the complete stanza docs at https://dune.readthedocs.io/en/stable/reference/dune-project/index.html
