.> UNUSED EXPORTED VALUES:
=========================
./examples/docs/coding_style/bind/bind.ml:2: v

./examples/docs/coding_style/opt/opt.ml:14: add_index_to_negative

./examples/docs/coding_style/seq/seq.ml:2: compute_answer

./examples/docs/coding_style/unit/unit.ml:2: compute_answer

./examples/docs/exported_values/code_constructs/function/function_lib.mli:7: unused

./examples/docs/exported_values/code_constructs/functor/functor_lib.mli:9: F.internally_used
./examples/docs/exported_values/code_constructs/functor/functor_lib.mli:10: F.unused
./examples/docs/exported_values/code_constructs/functor/functor_lib.mli:14: Internal_param.used_required
./examples/docs/exported_values/code_constructs/functor/functor_lib.mli:15: Internal_param.unused_required
./examples/docs/exported_values/code_constructs/functor/functor_lib.mli:25: Internal_app.internally_used
./examples/docs/exported_values/code_constructs/functor/functor_lib.mli:26: Internal_app.unused

./examples/docs/exported_values/code_constructs/incl_same_name/incl_with_intf/with_intf.mli:4: redefined_unused
./examples/docs/exported_values/code_constructs/incl_same_name/incl_with_intf/without_intf.mli:4: redefined_unused

./examples/docs/exported_values/code_constructs/incl_same_name/incl_without_intf/with_intf.ml:4: redefined_unused
./examples/docs/exported_values/code_constructs/incl_same_name/incl_without_intf/without_intf.ml:4: redefined_unused

./examples/docs/exported_values/code_constructs/incl_same_name/to_incl/with_intf.mli:2: unused
./examples/docs/exported_values/code_constructs/incl_same_name/to_incl/with_intf.mli:4: redefined_unused
./examples/docs/exported_values/code_constructs/incl_same_name/to_incl/with_intf.mli:5: redefined_used
./examples/docs/exported_values/code_constructs/incl_same_name/to_incl/without_intf.ml:2: unused
./examples/docs/exported_values/code_constructs/incl_same_name/to_incl/without_intf.ml:4: redefined_unused
./examples/docs/exported_values/code_constructs/incl_same_name/to_incl/without_intf.ml:5: redefined_used

./examples/docs/exported_values/code_constructs/include/include_lib.ml:5: Original.unused
./examples/docs/exported_values/code_constructs/include/include_lib.ml:15: Redefine.unused

./examples/docs/exported_values/code_constructs/modsig/modsig_lib.ml:6: Original.unused
./examples/docs/exported_values/code_constructs/modsig/modsig_lib.ml:12: Alias_with_sig.used_by_requirement

./examples/docs/exported_values/code_constructs/modtyp/modtyp_lib.mli:18: M_redef.internally_used
./examples/docs/exported_values/code_constructs/modtyp/modtyp_lib.mli:19: M_redef.unused

./examples/docs/exported_values/code_constructs/module/module_lib.mli:5: M.internally_used
./examples/docs/exported_values/code_constructs/module/module_lib.mli:6: M.unused

./examples/docs/exported_values/hello_world/hello_world_with_intf.mli:2: hello
./examples/docs/exported_values/hello_world/hello_world_with_intf.mli:3: goodbye
./examples/docs/exported_values/hello_world/hello_world_with_intf.mli:4: world

./examples/docs/methods/code_constructs/factory_fun/factory_fun_bin.ml:2: unused_factory

./examples/docs/methods/code_constructs/immediate_object/immediate_object_bin.ml:2: unused_obj

./examples/docs/optional_arguments/code_constructs/hof/hof_bin.ml:9: add_index

./examples/docs/optional_arguments/code_constructs/internal_app/internal_app_lib.mli:2: max
./examples/docs/optional_arguments/code_constructs/internal_app/internal_app_lib.mli:3: min

Nothing else to report in this section
--------------------------------------------------------------------------------


.> UNUSED METHODS:
=================
./examples/docs/methods/code_constructs/alias/alias_lib.mli:2: original#unused

./examples/docs/methods/code_constructs/class/class_bin.ml:2: unused_class#unused_method
./examples/docs/methods/code_constructs/class/class_lib.mli:2: int_stack#reset

./examples/docs/methods/code_constructs/coercion/coercion_lib.mli:2: obj#unused

./examples/docs/methods/code_constructs/constructor/constructor_bin.ml:2: unused_class#unused_method
./examples/docs/methods/code_constructs/constructor/constructor_lib.mli:2: int_stack#reset

./examples/docs/methods/code_constructs/factory_fun/factory_fun_bin.ml:2: unused_factory#unused_method
./examples/docs/methods/code_constructs/factory_fun/factory_fun_lib.mli:2: get_stack#reset

./examples/docs/methods/code_constructs/factory_fun_indir/factory_fun_indir.ml:2: factory_with_intermediate_binding#unused
./examples/docs/methods/code_constructs/factory_fun_indir/factory_fun_indir.ml:13: random_factory#unused

./examples/docs/methods/code_constructs/immediate_object/immediate_object_bin.ml:2: unused_obj#unused_method
./examples/docs/methods/code_constructs/immediate_object/immediate_object_lib.mli:2: int_stack#reset

./examples/docs/methods/code_constructs/inheritance/inheritance_lib.mli:2: parent#unused

./examples/docs/methods/code_constructs/polymorphic_class/polymorphic_class_lib.mli:2: stack#reset

Nothing else to report in this section
--------------------------------------------------------------------------------


.> UNUSED CONSTRUCTORS/RECORD FIELDS:
====================================
./examples/docs/fields_and_constructors/code_constructs/equal_types/all_internal.mli:9: sum.Unused
./examples/docs/fields_and_constructors/code_constructs/equal_types/all_internal.mli:18: product.unused
./examples/docs/fields_and_constructors/code_constructs/equal_types/definitions.ml:8: sum.Unused
./examples/docs/fields_and_constructors/code_constructs/equal_types/definitions.ml:16: product.unused
./examples/docs/fields_and_constructors/code_constructs/equal_types/via_hidden_equations.mli:8: sum.Unused
./examples/docs/fields_and_constructors/code_constructs/equal_types/via_hidden_equations.mli:16: product.unused
./examples/docs/fields_and_constructors/code_constructs/equal_types/via_include.mli:8: sum.Unused
./examples/docs/fields_and_constructors/code_constructs/equal_types/via_include.mli:16: product.unused
./examples/docs/fields_and_constructors/code_constructs/equal_types/via_module_alias.mli:9: Alias.sum.Unused
./examples/docs/fields_and_constructors/code_constructs/equal_types/via_module_alias.mli:17: Alias.product.unused

./examples/docs/fields_and_constructors/code_constructs/gadt/gadt_lib.mli:4: gadt.Float

./examples/docs/fields_and_constructors/code_constructs/inline_record/inline_record_lib.mli:4: t.Left
./examples/docs/fields_and_constructors/code_constructs/inline_record/inline_record_lib.mli:5: t.Right

./examples/docs/fields_and_constructors/code_constructs/polymorphic_type/polymorphic_type_lib.mli:2: either.Right
./examples/docs/fields_and_constructors/code_constructs/polymorphic_type/polymorphic_type_lib.mli:3: both.left

Nothing else to report in this section
--------------------------------------------------------------------------------


.> OPTIONAL ARGUMENTS: ALWAYS:
=============================
./examples/docs/coding_style/opt/opt.ml:15: ?index

./examples/docs/optional_arguments/code_constructs/external_app/external_app_lib.mli:3: ?max

./examples/docs/optional_arguments/code_constructs/hof/hof_bin.ml:2: ?index
./examples/docs/optional_arguments/code_constructs/hof/hof_bin.ml:6: ?index

./examples/docs/optional_arguments/code_constructs/internal_app/internal_app_lib.ml:9: ?max

./examples/docs/optional_arguments/code_constructs/intext_app/intext_app_lib.ml:9: ?max
./examples/docs/optional_arguments/code_constructs/intext_app/intext_app_lib.mli:2: ?min

./examples/docs/optional_arguments/code_constructs/partial_app/partial_app_bin.ml:2: ?x

./examples/docs/optional_arguments/code_constructs/total_app/total_app_bin.ml:2: ?x

./examples/docs/optional_arguments/limitations/relaying/relaying_bin.ml:2: ?x

Nothing else to report in this section
--------------------------------------------------------------------------------


.> OPTIONAL ARGUMENTS: NEVER:
============================
./examples/docs/optional_arguments/code_constructs/external_app/external_app_lib.mli:2: ?min

./examples/docs/optional_arguments/code_constructs/internal_app/internal_app_lib.ml:2: ?min

./examples/docs/optional_arguments/code_constructs/intext_app/intext_app_lib.ml:2: ?min
./examples/docs/optional_arguments/code_constructs/intext_app/intext_app_lib.mli:3: ?max

./examples/docs/optional_arguments/code_constructs/total_app/total_app_bin.ml:2: ?y

./examples/docs/optional_arguments/limitations/relaying/relaying_bin.ml:4: ?x

Nothing else to report in this section
--------------------------------------------------------------------------------


.> CODING STYLE:
===============
./examples/docs/coding_style/bind/bind.ml:3: let x = ... in x (=> useless binding)

./examples/docs/coding_style/opt/opt.ml:2: val f: ... -> (... -> ?_:_ -> ...) -> ...

./examples/docs/coding_style/seq/seq.ml:3: let () = ... in ... (=> use sequence)

./examples/docs/coding_style/unit/unit.ml:2: unit pattern input
./examples/docs/coding_style/unit/unit.ml:3: let () = ... in ... (=> use sequence)
./examples/docs/coding_style/unit/unit.ml:3: unit pattern print
./examples/docs/coding_style/unit/unit.ml:5: unit pattern r

./examples/docs/exported_values/code_constructs/functor/functor_lib.ml:16: unit pattern used_required
./examples/docs/exported_values/code_constructs/functor/functor_lib.ml:17: unit pattern unused_required
./examples/docs/exported_values/code_constructs/functor/functor_lib.ml:21: unit pattern used_required
./examples/docs/exported_values/code_constructs/functor/functor_lib.ml:22: unit pattern unused_required

./examples/docs/exported_values/code_constructs/include/include_lib.ml:3: unit pattern used_directly
./examples/docs/exported_values/code_constructs/include/include_lib.ml:4: unit pattern used_indirectly
./examples/docs/exported_values/code_constructs/include/include_lib.ml:5: unit pattern unused
./examples/docs/exported_values/code_constructs/include/include_lib.ml:14: unit pattern used_directly
./examples/docs/exported_values/code_constructs/include/include_lib.ml:15: unit pattern unused

./examples/docs/exported_values/code_constructs/modsig/modsig_lib.ml:3: unit pattern used_directly
./examples/docs/exported_values/code_constructs/modsig/modsig_lib.ml:4: unit pattern used_indirectly
./examples/docs/exported_values/code_constructs/modsig/modsig_lib.ml:5: unit pattern used_by_requirement
./examples/docs/exported_values/code_constructs/modsig/modsig_lib.ml:6: unit pattern unused

./examples/docs/exported_values/code_constructs/modtyp/modtyp_lib.ml:11: unit pattern externally_used
./examples/docs/exported_values/code_constructs/modtyp/modtyp_lib.ml:12: unit pattern internally_used
./examples/docs/exported_values/code_constructs/modtyp/modtyp_lib.ml:13: unit pattern unused
./examples/docs/exported_values/code_constructs/modtyp/modtyp_lib.ml:14: unit pattern unused_unexported

./examples/docs/exported_values/code_constructs/module/module_lib.ml:4: unit pattern externally_used
./examples/docs/exported_values/code_constructs/module/module_lib.ml:5: unit pattern internally_used
./examples/docs/exported_values/code_constructs/module/module_lib.ml:6: unit pattern unused
./examples/docs/exported_values/code_constructs/module/module_lib.ml:7: unit pattern unused_unexported

./examples/docs/methods/code_constructs/factory_fun_indir/factory_fun_indir.ml:20: let x = ... in x (=> useless binding)

./examples/docs/optional_arguments/code_constructs/hof/hof_bin.ml:2: val f: ... -> (... -> ?_:_ -> ...) -> ...

Nothing else to report in this section
--------------------------------------------------------------------------------


